### ISSUE TITLE
Adicionar google analitics

### ISSUE THREAD

**Issue by alexferreira-invillia** [alexferreiradev/gerenciador_horas_trabalho#125]
## Contexto 
Adicionar rasteamento, pois como ficará aberto para qualquer um usar, vamos medir para ver se compensa colocar algo de ads. 

## Refinamento 

1. O que precisa ser adicionado no HTML ? Tag google do fluxo de dados. 
3. O que precisa gerar no dash para colocar no html ? Propriedade (site) e tag. 
4. Precisa ser novo site no dash da google ? Sim, pois cada propriedade é um site que tem mais de um fluxo de dados. 

[Referencia oficial](https://support.google.com/analytics/answer/9304153?hl=pt-BR#zippy=%2Cadicione-a-tag-do-google-diretamente-%C3%A0s-suas-p%C3%A1ginas-da-web)

## Tarefas

- [x] Gerar tag 
- [x] Colocar tag em HTML
- [x] Testar tag em stage

**Comment by alexferreira-invillia** [comment]
Precisa da tag criada na conta google, aguardando a criacao.

**Comment by alexferreiradev** [comment]
Tag criada: 
```html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-40JWGD805L"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-40JWGD805L');
</script>
```
