### ISSUE TITLE
Criar Logotipo e icone para aplicação

### ISSUE THREAD

**Issue by alexferreiradev** [alexferreiradev/gerenciador_horas_trabalho#26]
Icone para pin tab

- logotipo para cabeçalho ou rodape

**Comment by alexferreira-invillia** [comment]
Planejamento técnico:

- Palavras relacionadas: lancamento, work, trabalho, 
- Icones relacionados: download, down, relogio, registro, trabalhado no dia, hora extra.

Criar scratch no inkscape. Criar versao mono color.

**Comment by alexferreira-invillia** [comment]
Criado draft no inkscape.

**Comment by alexferreira-invillia** [comment]
![image](https://github.com/alexferreiradev/gerenciador_horas_trabalho/assets/95075873/271a7947-0eb8-4d61-bf3e-c24e473b9358)
