### ISSUE TITLE
Criar wiki para aplicação

### ISSUE THREAD

**Issue by alexferreiradev** [alexferreiradev/gerenciador_horas_trabalho#27]
Adicionar wiki com imagens de principais funções no github. 

- Adicionar link para github wiki no rodape da aplicação (#35 ).
- Adicionar link para wiki no readme do projeto

**Comment by alexferreira-invillia** [comment]
Criado wiki do github. Testar clone de wiki local para fazer edicao no idea

**Comment by alexferreira-invillia** [comment]
Tarefas a fazer ainda:

- [ ] Linkar readme com wiki
- [ ] Criar card - replan comece a usar com um exemplo simples de uso completo
