### ISSUE TITLE
Numero de tarefa ter historico de tarefas do dia anterior

### ISSUE THREAD

**Issue by alexferreira-invillia** [alexferreiradev/gerenciador_horas_trabalho#99]
Ao criar uma tarefa em um dia e não ter finalizado, o dev vai lançar horas na tarefa no dia seguinte. Portanto, o dev poderia utilizar um histórico de tarefas que já lançou algum lançamento, e não precisa criar novamente o numero da tarefa. 

- Levantar limitações
- Levantar total de historico 
- Terá como editar este historico ? 
- Terá como limpar o historico  ?
- Tera como exportar este historico ?

**Comment by alexferreiradev** [comment]
## Refinamento

Armazenamento
Manter uma lista de tarefas apos clicar em "iniciar dia". Esta lista seria salva no disco e exportada em json. 
Dados que devem conter: key, totalSemLancamentos, 

Remoção da lista
Seria removido da lista as tarefas que estão sem lançamentos a x dias. Caso seja usado para algum lançamento, resetar o total. 

## Tarefas

- [x] Criar novo state de lista de tarefas
- [x] Alterar load dashboard para setar state de lista de tarefas lendo de storage
- [x] Adicionar label em resumo com total de tarefas em cache com um botão para poder futuramente editar
- [x] Alterar memo para lista de tarefas para usar novo state como adicional a lista de lancamentos 
- [x] Alterar função de iniciar dia. Colocar lista de tarefas em storage
- [x] Alterar função de iniciar dia. Atualizar lista de tarefas, removendo tarefas nao usadas dentro de 10 dias
- [x] Alterar salvar JSON com lista de tarefas
